#
# Makefile for the STM32 platform files
#

obj-$(CONFIG_MACH_STM32)	+= stm32_platform.o timer.o clock.o \
				   iomux.o reboot.o
obj-$(CONFIG_SERIAL_STM32)	+= uart.o
obj-$(CONFIG_STM32_ETHER)	+= eth.o
obj-$(CONFIG_MTD_PHYSMAP)	+= flash.o
obj-$(CONFIG_MMC_ARMMMCI)	+= sdcard.o
obj-$(CONFIG_STM32_DMA)		+= dmainit.o
