#
# Makefile for the Freescale Kinetis platform files
#

obj-$(CONFIG_MACH_KINETIS)	+= kinetis_platform.o timer.o clock.o \
				   iomux.o power.o cache.o
obj-$(CONFIG_SERIAL_KINETIS)	+= uart.o
obj-$(CONFIG_KINETIS_MAC)	+= eth.o
obj-$(CONFIG_MTD_NAND_FSL_NFC)	+= nand.o
obj-$(CONFIG_KINETIS_FB)	+= fb.o
obj-$(CONFIG_I2C_GPIO)		+= i2c-gpio.o
obj-$(CONFIG_KINETIS_EDMA)	+= dmainit.o dmac.o
obj-$(CONFIG_USB_EHCI_MXC)	+= ehci.o
obj-$(CONFIG_USB_KHCI_HCD)	+= khci.o
obj-$(CONFIG_KINETIS_SPI_GPIO)	+= spi-gpio.o
obj-$(CONFIG_GPIOLIB)		+= gpio.o
obj-$(CONFIG_MMC_ESDHC)		+= esdhc.o
obj-$(CONFIG_SPI_KINETIS)	+= spi.o
obj-$(CONFIG_RTC_DRV_KINETIS)	+= rtc.o
obj-$(CONFIG_SUSPEND)		+= pm.o suspend.o
