#
# Makefile for the Freescale Kinetis platform files
#

obj-$(CONFIG_MACH_KINETIS)	+= kinetis_platform.o timer.o clock.o \
				   iomux.o power.o
obj-$(CONFIG_SERIAL_KINETIS)	+= uart.o
obj-$(CONFIG_KINETIS_MAC)	+= eth.o
