#
# Makefile for the NXP LPC178x/7x platform files
#

obj-$(CONFIG_MACH_LPC178X)	+= lpc178x_platform.o timer.o clock.o \
				   iomux.o reboot.o power.o
obj-$(CONFIG_SERIAL_8250)	+= uart.o
obj-$(CONFIG_MTD_PHYSMAP)	+= flash.o
