#
# Makefile for the Actel SmartFusion2 platform files
#

obj-$(CONFIG_MACH_M2S)		+= m2s_platform.o timer.o clock.o \
				   iomux.o reboot.o
obj-$(CONFIG_SERIAL_8250)	+= uart.o
obj-$(CONFIG_SPI_M2S)		+= spi.o
obj-$(CONFIG_M2S_ETH)		+= eth.o
obj-$(CONFIG_I2C_A2F)		+= i2c.o
obj-$(CONFIG_M2S_MSS_USB)	+= usb.o
obj-$(CONFIG_GPIOLIB)		+= gpio.o
