# File: drivers/net/arm/Makefile
#
# Makefile for the ARM network device drivers
#

obj-$(CONFIG_ARM_AM79C961A)	+= am79c961a.o
obj-$(CONFIG_ARM_ETHERH)	+= etherh.o
obj-$(CONFIG_ARM_ETHER3)	+= ether3.o
obj-$(CONFIG_ARM_ETHER1)	+= ether1.o
obj-$(CONFIG_ARM_AT91_ETHER)	+= at91_ether.o
obj-$(CONFIG_ARM_KS8695_ETHER)	+= ks8695net.o
obj-$(CONFIG_EP93XX_ETH)	+= ep93xx_eth.o
obj-$(CONFIG_IXP4XX_ETH)	+= ixp4xx_eth.o
obj-$(CONFIG_W90P910_ETH)	+= w90p910_ether.o
obj-$(CONFIG_STM32_ETHER)	+= stm32_eth.o
obj-$(CONFIG_LPC178X_ETHER)	+= lpc178x_eth.o
obj-$(CONFIG_M2S_ETH)		+= m2s_eth.o
