#
# Makefile for the NXP LPC18xx platform files
#

obj-$(CONFIG_MACH_LPC18XX)	+= lpc18xx_platform.o timer.o clock.o \
				   iomux.o wdt.o
obj-$(CONFIG_SERIAL_8250)	+= uart.o
obj-$(CONFIG_STM32_ETHER)	+= eth.o
obj-$(CONFIG_MTD_PHYSMAP)	+= nor-flash.o
obj-$(CONFIG_SPI_PL022)		+= spi.o
obj-$(CONFIG_I2C_LPC2K)		+= i2c.o
