#
# Makefile for the NXP LPC18xx platform files
#

obj-$(CONFIG_MACH_LPC18XX)	+= lpc18xx_platform.o timer.o clock.o \
				   iomux.o
obj-$(CONFIG_SERIAL_8250)	+= uart.o
obj-$(CONFIG_LPC18XX_MAC)	+= eth.o
obj-$(CONFIG_MTD_PHYSMAP)	+= nor-flash.o
