#
# Makefile for the NXP LPC18xx platform files
#

obj-$(CONFIG_MACH_LPC18XX)	+= lpc18xx_platform.o timer.o clock.o \
				   iomux.o wdt.o dma.o
obj-$(CONFIG_USB_EHCI_LPC43XX)	+= ehci.o
obj-$(CONFIG_STM32_ETHER)	+= eth.o
obj-$(CONFIG_FB_ARMCLCD)	+= fb.o
obj-$(CONFIG_I2C_LPC2K)		+= i2c.o
obj-$(CONFIG_SND_LPC3XXX_SOC)	+= i2s.o
obj-$(CONFIG_MMC_DW)		+= mmc.o
obj-$(CONFIG_MTD_PHYSMAP)	+= nor-flash.o
obj-$(CONFIG_RTC_DRV_LPC178X)	+= rtc.o
obj-$(CONFIG_SPI_PL022)		+= spi.o
obj-$(CONFIG_MTD_M25P80_SPIFI)	+= spifi.o
obj-$(CONFIG_SERIAL_8250)	+= uart.o
