# LPC3XXX Platform Support
snd-soc-lpc3xxx-objs := lpc3xxx-pcm.o
snd-soc-lpc3xxx-i2s-objs := lpc3xxx-i2s.o

obj-$(CONFIG_SND_LPC3XXX_SOC) += snd-soc-lpc3xxx.o snd-soc-lpc3xxx-i2s.o

# LPC3XXX Machine Support
snd-soc-lpc3xxx-uda1380-objs := lpc3xxx-uda1380.o

obj-$(CONFIG_SND_LPC3XXX_SOC_I2S_UDA1380) += snd-soc-lpc3xxx-uda1380.o
