#
# Makefile for the Actel SmartFusion platform files
#

obj-$(CONFIG_MACH_A2F)		+= a2f_platform.o timer.o clock.o \
				   iomux.o fpga.o reboot.o
obj-$(CONFIG_SERIAL_8250)	+= uart.o
obj-$(CONFIG_CORE10100)		+= eth.o
obj-$(CONFIG_SPI_A2F)		+= spi.o
obj-$(CONFIG_I2C_A2F)		+= i2c.o
obj-$(CONFIG_MTD_PHYSMAP)	+= flash.o
obj-$(CONFIG_GPIOLIB)		+= gpio.o

